There are many function to modify array using these function we can insert,update,delete

### insert
#### Syntax 
##### np.insert(array,positionIndex, value,axis)
###### array = original array 
###### index = means where you want to insert element on array
###### value = which value you want to add
###### axis = means which dimension you want to insert multi dimension. In 1-D array axis is none by default 

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
new_arr = np.insert(arr,2,0)
print(new_arr)

[1 2 0 3 4 5 6]


In 2-D array

In [3]:
arr_2D = np.array([[1,2],[3,4]])
print("Before insertion:\n",arr_2D)
new_arr = np.insert(arr_2D,1,[5,6], axis=0)
print("\n after insertion:\n",new_arr)


Before insertion:
 [[1 2]
 [3 4]]

 after insertion:
 [[1 2]
 [5 6]
 [3 4]]


Append

In [4]:
arr = np.array([1,2,3,4,5])
new_arr = np.append(arr,[6,7,8])
print(new_arr)

[1 2 3 4 5 6 7 8]


Concatinate:-   used to join two array

In [5]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

new_arr = np.concatenate((arr1,arr2))
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10]


 ## Delete

#### Delete function with 1-D array

In [6]:
arr = np.array([1,2,3,4,5,6,7])
new_arr = np.delete(arr,1)  # remove 2 in array means second position
print(new_arr)

[1 3 4 5 6 7]


#### Delete function with 2-D array

In [12]:
arr_2D = np.array([[1,2,3],[4,5,6]])

new_arr_2D = np.delete(arr_2D,1,axis=0)
print(new_arr_2D)
print("\n --------------------------- \n")
new_arr_2D = np.delete(arr_2D,2,axis=1)
print(new_arr_2D)

[[1 2 3]]

 --------------------------- 

[[1 2]
 [4 5]]


### Stacking

In [14]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([6,7,8,9])
print(np.vstack((arr1,arr2))) # verticaly stack
print(np.hstack((arr1,arr2))) # horizontaly stack

[[1 2 3 4]
 [6 7 8 9]]
[1 2 3 4 6 7 8 9]


### Spliting

In [17]:
arr = np.array([1,2,3,4,5,6])
print(np.split(arr,2))

[array([1, 2, 3]), array([4, 5, 6])]
