Creating array from python list

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


Default Values

In [2]:
arr = np.zeros(6)
print(arr)

[0. 0. 0. 0. 0. 0.]


Ones function 

In [3]:
arr = np.ones(6)
print(arr)

[1. 1. 1. 1. 1. 1.]


Full function to creating array where every element start with a specific number
np.full(shapes,number)

In [4]:
arr = np.full(6, 42)
print(arr)

[42 42 42 42 42 42]


Creating sequences of numbers in numpy

arange()

In [ ]:
arr = np.arange(5)   # Start at 0, end before 5
print(arr)

[0 1 2 3 4]


In [ ]:
arr = np.arange(1,5)   # Start at 1, end before 5 and can be start array from any number like 1 to 5, 2 to 10, 100 to 200 etc.
print(arr)

[1 2 3 4]


In [7]:
arr = np.arange(1, 10, 2) # Start at 1, end before 10 and step by 2
print(arr)

[1 3 5 7 9]


 Creating identity matrices

In [8]:
arr = np.eye(3)  # Identity matrix of size 3x3 with 1s on the diagonal and 0s elsewhere
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
