In [1]:
import numpy as np

0 Dimension Array

In [4]:
zero_dimensional_array = np.array(42)
print(zero_dimensional_array)

42


1-D array

In [2]:
one_dimensional_array = np.array([1,2,3,4,5,6])
print(one_dimensional_array)

[1 2 3 4 5 6]


2-D array

In [5]:
two_dimensional_array = np.array([[1,2,3],[4,5,6]])
print(two_dimensional_array)

[[1 2 3]
 [4 5 6]]


3-D array

In [8]:
three_dimensional_array = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(three_dimensional_array)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
