In [1]:
import numpy as np

Mathamatical Operation in 1-D ARRAY

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
arr = arr+2
print(arr)

[3 4 5 6 7]


In [4]:
arr = arr*2
print(arr)

[ 6  8 10 12 14]


In [5]:
arr = arr-2
print(arr)

[ 4  6  8 10 12]


In [6]:
arr = arr/2
print(arr)

[2. 3. 4. 5. 6.]


In [8]:
arr = arr % 2
print(arr)

[0. 1. 0. 1. 0.]


Mathematical Operation in 2-D ARRAY

In [19]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [20]:
arr = arr+2
print(arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [21]:
arr = arr-1
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
arr = arr*3
print(arr)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [23]:
arr = arr%2
print(arr)

[[1 0 1]
 [0 1 0]
 [1 0 1]]


Mathematical Operation between two matrices

In [25]:
arr2 = np.arange(9).reshape(3,3)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [27]:
addition = arr+arr2
print(addition)

[[1 1 3]
 [3 5 5]
 [7 7 9]]


In [28]:
mul = addition * arr2
print(mul)

[[ 0  1  6]
 [ 9 20 25]
 [42 49 72]]
