Reshaping :-   Change dimension of array without change any element of array

In [8]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print("before reshaping: \n\n",arr)
reshape = arr.reshape(3,2)
print("After reshaping: \n\n",reshape)


before reshaping: 

 [1 2 3 4 5 6]
After reshaping: 

 [[1 2]
 [3 4]
 [5 6]]


Reshape return view not copy if we change value of reshaping array then it will also effect on old array
for example

In [11]:
arr = np.array([1,2,3,4,5,6])
print("before reshaping: \n\n",arr)
reshape = arr.reshape(3,2)
print("After reshaping: \n\n",reshape)
print("\n\n")
reshape[0,1] = 20
print(reshape)
print(arr)

before reshaping: 

 [1 2 3 4 5 6]
After reshaping: 

 [[1 2]
 [3 4]
 [5 6]]



[[ 1 20]
 [ 3  4]
 [ 5  6]]
[ 1 20  3  4  5  6]


Ravel & Flattern:- Use to convert 2-D or 3-D array to 1-D ARRAY

##### Ravel() => view
##### flattern() => copy

In [12]:
twoDarr = np.array([[1,2,3],[1,2,3]])
print(twoDarr.ravel())
print(twoDarr.flatten())

[1 2 3 1 2 3]
[1 2 3 1 2 3]
